# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlab2.proto\x12\x04lab2\"\x1f\n\rGetMapRequest\x12\x0e\n\x06MapReq\x18\x01 \x01(\t\"\x1d\n\x0bGetMapReply\x12\x0e\n\x06values\x18\x01 \x01(\t\"\"\n\rGetRoverMoves\x12\x11\n\treoverReq\x18\x01 \x01(\t\"\'\n\x10ReturnRoverMoves\x12\x13\n\x0bRoverStream\x18\x01 \x01(\t\"%\n\x0cSerialNumReq\x12\x15\n\rSerNumRequest\x18\x01 \x01(\t\"%\n\x0eSerialNumReply\x12\x13\n\x0bSerNumReply\x18\x04 \x01(\x05\x32:\n\x04\x42omb\x12\x32\n\x06GetMap\x12\x13.lab2.GetMapRequest\x1a\x11.lab2.GetMapReply\"\x00\x32G\n\nRoverMoves\x12\x39\n\x08GetMoves\x12\x13.lab2.GetRoverMoves\x1a\x16.lab2.ReturnRoverMoves\"\x00\x32J\n\x0cSerialNumber\x12:\n\x0cGetSerialNum\x12\x12.lab2.SerialNumReq\x1a\x14.lab2.SerialNumReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETMAPREQUEST._serialized_start=20
  _GETMAPREQUEST._serialized_end=51
  _GETMAPREPLY._serialized_start=53
  _GETMAPREPLY._serialized_end=82
  _GETROVERMOVES._serialized_start=84
  _GETROVERMOVES._serialized_end=118
  _RETURNROVERMOVES._serialized_start=120
  _RETURNROVERMOVES._serialized_end=159
  _SERIALNUMREQ._serialized_start=161
  _SERIALNUMREQ._serialized_end=198
  _SERIALNUMREPLY._serialized_start=200
  _SERIALNUMREPLY._serialized_end=237
  _BOMB._serialized_start=239
  _BOMB._serialized_end=297
  _ROVERMOVES._serialized_start=299
  _ROVERMOVES._serialized_end=370
  _SERIALNUMBER._serialized_start=372
  _SERIALNUMBER._serialized_end=446
# @@protoc_insertion_point(module_scope)
